# Generated by Django 5.2.4 on 2025-07-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                (
                    "ink_json_content",
                    models.JSONField(
                        blank=True,
                        help_text="The compiled JSON story content of the Ink story exported from Inky.",
                        null=True,
                    ),
                ),
                (
                    "available_languages",
                    models.ManyToManyField(
                        related_name="story", to="languatale.language"
                    ),
                ),
            ],
        ),
    ]
