# Generated by Django 5.2.4 on 2025-07-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languatale", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="available_languages",
            field=models.ManyToManyField(
                related_name="stories", to="languatale.language"
            ),
        ),
    ]
